# Permalinks
permalink:           pretty

# Setup
title:               Anthony Hu
tagline:             Personal blog - new baseurl live modif? try modif ok ok
url:                 https://anthonyhu.github.io/
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Anthony Hu
  url:               https://twitter.com/hu_anth
  email:             ah2029@cam.ac.uk

plugins:
  - jekyll-paginate
  - jekyll-gist
