# Permalinks
permalink:           pretty

# Setup
title:               Anthony Hu
tagline:
url:                 https://anthonyhu.github.io/
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Anthony Hu
  url:               https://twitter.com/hu_anth
  email:             anthony@wayve.ai

plugins:
  - jekyll-paginate
  - jekyll-gist

# Navigation bar
pages_list:
  Research: '/research'
  Blog posts: '/posts'

# Google Analytics ID
google_analytics: G-ZEX81SMNGH

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
disqus: "https-anthonyhu-github-io"

# Research posts
collections:
  research:
    output: true

# About
curriculum:
  - image: img/wayve.png
    title: Wayve
    info: 2019 - Present
    description: "Applied Scientist"
    url: https://wayve.ai/
  - image: img/cambridge.png
    title: University of Cambridge
    info: 2018 - 2022
    description: "PhD in Computer Vision"
    url: http://mi.eng.cam.ac.uk/Main/CVR
  - image: img/spotify.png
    title: Spotify
    info: 2017 - 2018
    description: "Research Scientist Intern"
    url: https://www.spotify.com/
  - image: img/oxford.png
    title: University of Oxford
    info: 2016 - 2017
    description: "MSc in Statistical Science"
    url: https://www.stats.ox.ac.uk/
  - image: img/telecom.png
    title: Telecom Paris
    info: 2014-2017
    description: Diplôme d'Ingénieur
    url: https://www.telecom-paris.fr/
  - image: img/saint-louis.png
    title: Lycee Saint-Louis
    info: 2012-2014
    description: Classes Preparatoires (Maths and Physics)
    url: https://lycee-saintlouis.fr/
